server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
swagger:
  resourcePackage: com.tr.microsvcs.dw.resources
defaultMaxResults: 9999
clusterName: ORG-ELSCLUSTER-SAND
index: origin-v1
esNodes:
  - tr-es-cloud-org-elscluster-sand-3.amers2.cis.trcloud
  - tr-es-cloud-org-elscluster-sand-2.amers2.cis.trcloud
  - tr-es-cloud-org-elscluster-sand-1.amers2.cis.trcloud
